In [1]:
import pandas as pd
import numpy as np

In [2]:
teams=pd.read_csv("teams.csv")

In [7]:
teams

team  year  athletes  events   age  height  weight  prev_medals  medals
0     AFG  1964         8       8  22.0   161.0    64.2          0.0       0
1     AFG  1968         5       5  23.2   170.2    70.0          0.0       0
2     AFG  1972         8       8  29.0   168.3    63.8          0.0       0
3     AFG  1980        11      11  23.6   168.4    63.2          0.0       0
4     AFG  2004         5       5  18.6   170.8    64.8          0.0       0
...   ...   ...       ...     ...   ...     ...     ...          ...     ...
2009  ZIM  2000        26      19  25.0   179.0    71.1          0.0       0
2010  ZIM  2004        14      11  25.1   177.8    70.5          0.0       3
2011  ZIM  2008        16      15  26.1   171.9    63.7          3.0       4
2012  ZIM  2012         9       8  27.3   174.4    65.2          4.0       0
2013  ZIM  2016        31      13  27.5   167.8    62.2          0.0       0

[2014 rows x 9 columns]

In [10]:
X=teams[["athletes","prev_medals"]]
y=teams[["medals"]]

In [11]:
X

athletes  prev_medals
0            8          0.0
1            5          0.0
2            8          0.0
3           11          0.0
4            5          0.0
...        ...          ...
2009        26          0.0
2010        14          0.0
2011        16          3.0
2012         9          4.0
2013        31          0.0

[2014 rows x 2 columns]

In [12]:
y

medals
0          0
1          0
2          0
3          0
4          0
...      ...
2009       0
2010       3
2011       4
2012       0
2013       0

[2014 rows x 1 columns]

In [16]:
X["intercept"]=1
X=X[["intercept","athletes","prev_medals"]]
X

intercept  athletes  prev_medals
0             1         8          0.0
1             1         5          0.0
2             1         8          0.0
3             1        11          0.0
4             1         5          0.0
...         ...       ...          ...
2009          1        26          0.0
2010          1        14          0.0
2011          1        16          3.0
2012          1         9          4.0
2013          1        31          0.0

[2014 rows x 3 columns]

In [17]:
X_T=X.T
X_T

0     1     2     3     4     5     6     7     8     9     ...  \
intercept     1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   
athletes      8.0   5.0   8.0  11.0   5.0   4.0   6.0   3.0   4.0   5.0  ...   
prev_medals   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0  ...   

             2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  
intercept     1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
athletes     52.0  20.0  47.0  28.0  21.0  26.0  14.0  16.0   9.0  31.0  
prev_medals   0.0  15.0   0.0   0.0   0.0   0.0   0.0   3.0   4.0   0.0  

[3 rows x 2014 columns]

In [19]:
B = np.linalg.inv(X_T @ X) @ X_T @ y
B

medals
0 -1.961889
1  0.071112
2  0.734137

In [21]:
B.index=X.columns


medals
intercept   -1.961889
athletes     0.071112
prev_medals  0.734137

In [23]:
predictions = X @ B
predictions

medals
0    -1.392992
1    -1.606329
2    -1.392992
3    -1.179656
4    -1.606329
...        ...
2009 -0.112974
2010 -0.966319
2011  1.378315
2012  1.614667
2013  0.242587

[2014 rows x 1 columns]

In [25]:
SSR = ((y - predictions) ** 2).sum()
SSR

medals    290620.124598
dtype: float64

In [26]:
TSS = ((y - y.mean()) ** 2).sum()
TSS

medals    2.276322e+06
dtype: float64

In [27]:
R2 = 1 - (SSR / TSS)

In [51]:
from sklearn.linear_model import LinearRegression

In [52]:
model=LinearRegression()

In [53]:
X=teams[["athletes","prev_medals"]]
model.fit(X,y)

LinearRegression()

In [56]:
model.predict(X)

array([[-1.39299224],
       [-1.60632867],
       [-1.39299224],
       ...,
       [ 1.3783153 ],
       [ 1.61466709],
       [ 0.24258707]])

In [57]:
model.score(X,y)

0.8723290685786969

In [45]:
model.intercept_

array([ 5.61031572e+00,  7.22116766e-01,  2.96038655e-01,  1.61299445e-01,
        7.12607261e-02,  7.62096267e-02,  4.87331193e-02,  5.53742565e-02,
        5.11770697e-03, -5.93567316e-02, -2.55433273e-02, -3.88071921e-02,
       -2.22725385e-02, -1.85648471e-02, -2.18989305e-02, -3.36336824e-02,
       -1.55193087e-02, -3.38081427e-02, -4.13621033e-02, -4.53791892e-02,
       -6.91516308e-02, -4.83270692e-02, -5.40155444e-02, -5.45958033e-02,
       -4.50458602e-02, -4.59217157e-02, -6.48661641e-02, -6.03892780e-02,
       -5.56111044e-02, -6.59184484e-02, -5.51491933e-02, -8.49253542e-02,
       -5.96726883e-02, -5.42797855e-02, -3.73917537e-02, -7.82237053e-02,
       -5.00865328e-02, -5.45566106e-02, -3.96990632e-02, -5.00508262e-02,
       -6.13797082e-02, -5.71557120e-02, -7.37420310e-02, -4.84037984e-02,
       -7.89170643e-02, -7.15948002e-02, -6.95278945e-02, -7.01080613e-02,
       -3.52530567e-02, -6.13688613e-02, -8.90127916e-02, -6.16592748e-02,
       -6.99145347e-02, -

In [47]:
model.coef_

array([[ 9.59383464e-02, -3.78875736e+00],
       [ 1.36185671e-01, -2.17205460e+00],
       [ 1.17936663e-01, -1.42678212e+00],
       [ 1.21727935e-01, -1.37641368e+00],
       [ 8.16372948e-02, -5.25472805e-01],
       [ 1.04779265e-01, -9.34867625e-01],
       [ 9.62888431e-02, -7.75334757e-01],
       [ 4.92022362e-02, -1.45217983e-01],
       [ 8.76134903e-02, -6.12980153e-01],
       [ 9.07560452e-02, -6.91787973e-01],
       [ 7.02051250e-02, -3.69615731e-01],
       [ 7.05019218e-02, -3.92196143e-01],
       [ 3.48510157e-02, -4.30648621e-02],
       [ 6.28600538e-02, -2.87180183e-01],
       [ 4.21502265e-02, -9.42515301e-02],
       [ 6.29160603e-02, -2.85457877e-01],
       [ 4.39233844e-02, -1.06573532e-01],
       [ 3.90049782e-02, -8.18403007e-02],
       [ 4.16229314e-02, -1.16950827e-01],
       [ 1.64662495e-02,  6.44741774e-02],
       [ 7.58415531e-02, -4.32274477e-01],
       [ 2.21607899e-02,  2.00292781e-02],
       [ 6.40286176e-02, -2.84310091e-01],
       [ 6.